### ISSUE TITLE
Extrinsic params

### ISSUE THREAD

**Issue by ManChrys** [JokerJohn/LIO-SAM-6AXIS-INTENSITY#1]
Hello,

how can i calculate translation and rotation from lidar to imu ? Any help ?

> extrinsicTrans: [ -0.047781, 0.007303, -0.026583 ]
>  extrinsicRot: [ 0.9999872, -0.0010636, -0.0049547,
                  0.0010324,  0.9999796, -0.0062985,
                  0.0049613,  0.0062933,  0.9999679 ]
>  extrinsicRPY: [ 0.9999872, -0.0010636, -0.0049547,
                  0.0010324,  0.9999796, -0.0062985,
                  0.0049613,  0.0062933,  0.9999679 ]

Thanks in advance

**Comment by JokerJohn** [comment]
Pls refer to this repo [kalibr](https://github.com/ethz-asl/kalibr)

**Comment by ManChrys** [comment]
> Pls refer to this repo [kalibr](https://github.com/ethz-asl/kalibr)

But this repo doesn't include LiDAR-imu calib. It has imu-imu camera-imu etc. correct me if I am wrong but I didn't find anything about LiDAR .

**Comment by ManChrys** [comment]
one of the contributors said that tis package doesnt support lidar-imu calibration.

https://github.com/ethz-asl/kalibr/issues/371#issuecomment-1106611682

**Comment by JokerJohn** [comment]
calibrate lidar and camera，and then  camera and imu，you can get the extrinsic between lidar and imu.

**Comment by ManChrys** [comment]
> calibrate lidar and camera，and then camera and imu，you can get the extrinsic between lidar and imu.

ok thank you.
